spring:
  jpa:
    show-sql: false
  datasource:
    hikari:
      maximum-pool-size: 5

rate-limit:
  requests-per-minute: 500

logging:
  level:
    com.movie.recommendation: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
