-- V5: Create recommendations table
-- This table stores pre-computed movie recommendations for users
-- Generated by a scheduled job every 6 hours

CREATE TABLE recommendations (
    id              BIGSERIAL       PRIMARY KEY,
    user_id         BIGINT          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    movie_id        BIGINT          NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    score           NUMERIC(5,4)    NOT NULL CHECK (score >= 0 AND score <= 1),
    strategy_type   VARCHAR(30)     NOT NULL
                                    CHECK (strategy_type IN ('COLLABORATIVE', 'CONTENT_BASED')),
    generated_at    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, movie_id, strategy_type)
);

-- Index for fast retrieval of user recommendations sorted by score
CREATE INDEX idx_recommendations_user_score ON recommendations (user_id, score DESC);

-- Index for cleanup operations by generation time
CREATE INDEX idx_recommendations_generated_at ON recommendations (generated_at);

-- Index for strategy-based queries
CREATE INDEX idx_recommendations_strategy ON recommendations (strategy_type);
